name: 'Docker Publish'
description: 'Publish Docker images'
author: 'Marc Nuri'
branding:
  icon: upload-cloud
  color: blue
inputs:
  name:
    description: 'Name of the Docker image'
    required: true
  tag:
    description: 'Tag for the Docker image'
    required: false
  tag script:
    description: 'Script body to compute tag name for the Docker image, has context as the main function argument'
    required: false
  username:
    description: 'Username for Docker registry'
    required: true
  password:
    description: 'Password for Docker registry'
    required: true
  registry:
    description: 'Registry URL'
    required: false
  include pull requests:
    description: "Don't skip pull requests"
    required: false
runs:
  image: 'Dockerfile'
